const spells = [{
        name: "Convocar Aliado Natural I",
        image: "./images/fireball.png",
        level: "1",
        school: "conjuracion [Convocación]",
        components: "V, S, DF",
        castingTime: "1 asalto",
        range: "Corto (25 ft. + 5 ft./level)",
        efecto: "una criatura convocada",
        area: "",
        duration: "1 asalto /nivel (D)",
        savingThrow: "",
        spellResistance: "No",
        description: "Convoca a una criatura natural de Nivel 1 (Aguila, Buho, Lobo, Marsopa, Pulpo, Rata Terrible, Vivora Pequeña). Ésta aparecerá en el lugar que designes y actuará inemdiatamente durante tu turno, atacando a sus oponentes al máximo de sus capacidades.  Si puedes comunicarte con la criatura, podrás indicarle que no ataque, que ataque a enemigos concretos o que lleve a cabo otras acciones. Las criaturas no pueden ser convocadas a un entorno que no sea soportables para ellas.  A menos que se indique otra cosa, todas las criaturas son neutrales.",
    },
    {
        name: "Convocar Aliado Natural II",
        image: "./images/fireball.png",
        level: "2",
        school: "adivinacion [Convocación]",
        components: "V, S, DF",
        castingTime: "1 accion estandar",
        range: "Corto (25 ft. + 5 ft./level)",
        efecto: "una o más criaturas convocadas, dos cualesquiera no pueden distar mas de 30ft",
        area: " ",
        duration: "1 asalto /nivel (D)",
        savingThrow: "",
        spellResistance: "No",
        description: "Este conjuro convoca a una criatura natural de Nivel 2 (Calamar, Cocodrilo, Elemental Pequeño (cualquiera), Glotón, Hipogrifo, Murcielago Terrible, Oso Negro, Tejón Terrible, Tiburón Mediano, Vivora Mediana.) o 1d3 criaturas del mismo tipo de Nivel 1. Aparece en el lugar que designes y actua durante tu turno, atacando al máximo de sus capacidades. Si puedes comunicarte, podrás indicar que no ataque, que ataque a enemigos concretos o lleve a cabo otras acciones. No puede convocar ni conjurar, ni utilizar aptitudes de teleportación o viaje planario. No pueden ser convocadas a un entorno que no sea soportables para ellas. A menos que se indique otra cosa, todas las criaturas son neutrales.",
    },
    {
        name: "Convocar Aliado Natural III",
        image: "./images/fireball.png",
        level: "3",
        school: "abjuracion [Convocación]",
        components: "V, S, DF",
        castingTime: "1 asalto",
        range: "Corto (25 ft. + 5 ft./level)",
        efecto: "una o más criaturas convocadas, dos cualesquiera no pueden distar mas de 30ft",
        area: "",
        duration: "1 asalto /nivel (D)",
        savingThrow: "",
        spellResistance: "No",
        description: "Este conjuro convoca a una criatura natural de Nivel 3 (Aguila Gigante, Buho Gigante, Comadreja Terrible, Leon, Lobo Terrible, Satiro [CN, sin flautas], Serpiente Constrictor, Vivora Grande, Simio, Tiburon Grande, Thoqqua). 1d3 de Nivel 2 o 1d4+1 criaturas del mismo tipo de Nivel 1. Cuando usas un conjuro de convocaciones para traer criaturas de agua, aire, fuego, tierra, buenas, caoticas, legales o malignas, se convierte en un sortilegio de ese tipo.",
    },
    {
        name: "Convocar Aliado Natural IV",
        image: "./images/fireball.png",
        level: "4",
        school: "conjuracion [Convocación]",
        components: "V, S, DF",
        castingTime: "1 asalto",
        range: "Corto (25 ft. + 5 ft./level)",
        efecto: "una o más criaturas convocadas, dos cualesquiera no pueden distar mas de 30ft",
        area: "",
        duration: "1 asalto /nivel (D)",
        savingThrow: "",
        spellResistance: "No",
        description: "Una criatura de Nivel 4, 1d3 de nivel 3, o 1d4+1 de una lista de nivel inferior.",
    },
    // Add the other spells here...

    {
        name: "Llamar al relámpago (Completo)",
        image: "./images/fireball.png",
        level: "3",
        school: "Evocación [Electricidad]",
        components: "V, S",
        castingTime: "1 asalto",
        range: "Intermedio (100 ft. + 10 ft./level)",
        efecto: "Una o más líneas de relámpago verticales de 30 ft de largo.",
        area: "",
        duration: "1 minuto /nivel",
        savingThrow: "Reflejos mitad",
        spellResistance: "Si",
        description: "Inmediatamente tras completar el lanzamiento del conjuro y una vez por asalto a partir de entonces, puedes llamar un relámpago vertical de 5 pies de ancho y 30 de altura que causa 3d6 puntos de daño por electricidad. El relámpago lanza un impacto verticalmente desde cualquier punto que escojas dentro del alcance del conjuro (medido desde tu posición en cada momento). Cualquier criatura en la casilla objetivo o en el camino del relámpago resulta afectada.         No necesitas llamar un relámpago inmediatamente; puedes realizar antes otras acciones, incluso lanzar conjuros. Cada asalto después del primero puedes usar una acción estándar (concentrándote en el conjuro) para llamar a un relámpago. Puedes llamar un número total de relámpagos igual a tu nivel de lanzador (máximo 10 relámpagos).                Si estás en el exterior y en una zona de tormenta (lluviosa, con condiciones de nubosidad y viento o incluso un tornado, incluído el torbellino formado por un djinni o elemental de aire de al menos tamaño Grande) cada relámpago causará 3d10 puntos de daño por electricidad en lugar de 3d6. Este conjuro funciona en lugares cerrados o bajo tierra, pero no bajo el agua.",
    },
    {
        name: "Llamar al relámpago",
        image: "./images/llamar-al-relampago.png",
        level: "3",
        school: "Evocación [Electricidad]",
        components: "V, S",
        castingTime: "1 asalto",
        range: "Intermedio (100 ft. + 10 ft./level)",
        efecto: "Una o más líneas de relámpago verticales de 30 ft de largo.",
        area: "",
        duration: "1 minuto /nivel",
        savingThrow: "Reflejos mitad",
        spellResistance: "Si",
        description: "* Una vez por asalto puedes usar una acción estándar (concentrándote en el conjuro) para llamar a un relámpago vertical de 5 pies de ancho y 30 de altura que causa 3d6 puntos de daño por electricidad. ~* Puedes llamar un número total de relámpagos igual a tu nivel de lanzador (máximo 10 relámpagos). ~* Si estás en el exterior y en una zona de tormenta cada relámpago causará 3d10 puntos de daño por electricidad. ~* Este conjuro funciona en lugares cerrados o bajo tierra, pero no bajo el agua.",
    },
];

export {
    spells
};